name: Laravel Testing Workflow

on:
  workflow_call:
    inputs:
      branches:
        required: true
        type: array
        description: "Branches to trigger the workflow on"
      php_version:
        required: true
        type: string
        description: "PHP version to use"

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Composer Dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php_version }}

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.testing.example', '.env');"

      - name: Run Composer Install
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader --ignore-platform-req=ext-gd

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v39

      - name: Run Pint
        run: |
          ./vendor/bin/pint --test ${{ steps.changed-files.outputs.all_changed_files }}
      - name: Run PHPUnit Tests
        run: php artisan test
