name: Laravel Testing Workflow

on:
  workflow_call:
    inputs:
      php_version:
        required: true
        type: string
        description: "PHP version to use"
      isNodeEnabled:
        required: false
        type: boolean
        default: false
        description: "Whether to enable Node.js steps"
      node_version:
        required: false
        type: string
        description: "Node.js version to use if Node.js steps are enabled"

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Composer Dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Cache Node Modules
        if: ${{ inputs.isNodeEnabled }}
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}
          restore-keys: |
            node-

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php_version }}

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.testing.example', '.env');"

      - name: Run Composer Install
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader --ignore-platform-req=ext-gd

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v39
      
      - name: Install Node.js
        if: ${{ inputs.isNodeEnabled }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install NPM Dependencies
        if: ${{ inputs.isNodeEnabled }}
        run: |
          npm install

      - name: Run NPM Build
        if: ${{ inputs.isNodeEnabled }}
        run: |
          npm run build

      - name: Run Pint
        run: |
          ./vendor/bin/pint --test ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Run PHPUnit Tests
        run: |
          php artisan test
          if [ $? -eq 0 ]; then
            echo "Tests passed successfully."
            exit 0
          else
            echo "Tests failed."
            exit 1
          fi
